// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drones.proto

package org.example.grpc;

public final class Drones {
  private Drones() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VelocidadesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Velocidades)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 u = 1;</code>
     */
    int getU();

    /**
     * <code>int32 v = 2;</code>
     */
    int getV();

    /**
     * <code>int32 w = 3;</code>
     */
    int getW();

    /**
     * <code>int32 r = 4;</code>
     */
    int getR();
  }
  /**
   * Protobuf type {@code Velocidades}
   */
  public  static final class Velocidades extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Velocidades)
      VelocidadesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Velocidades.newBuilder() to construct.
    private Velocidades(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Velocidades() {
      u_ = 0;
      v_ = 0;
      w_ = 0;
      r_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Velocidades(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              u_ = input.readInt32();
              break;
            }
            case 16: {

              v_ = input.readInt32();
              break;
            }
            case 24: {

              w_ = input.readInt32();
              break;
            }
            case 32: {

              r_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.grpc.Drones.internal_static_Velocidades_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.grpc.Drones.internal_static_Velocidades_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.grpc.Drones.Velocidades.class, org.example.grpc.Drones.Velocidades.Builder.class);
    }

    public static final int U_FIELD_NUMBER = 1;
    private int u_;
    /**
     * <code>int32 u = 1;</code>
     */
    public int getU() {
      return u_;
    }

    public static final int V_FIELD_NUMBER = 2;
    private int v_;
    /**
     * <code>int32 v = 2;</code>
     */
    public int getV() {
      return v_;
    }

    public static final int W_FIELD_NUMBER = 3;
    private int w_;
    /**
     * <code>int32 w = 3;</code>
     */
    public int getW() {
      return w_;
    }

    public static final int R_FIELD_NUMBER = 4;
    private int r_;
    /**
     * <code>int32 r = 4;</code>
     */
    public int getR() {
      return r_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (u_ != 0) {
        output.writeInt32(1, u_);
      }
      if (v_ != 0) {
        output.writeInt32(2, v_);
      }
      if (w_ != 0) {
        output.writeInt32(3, w_);
      }
      if (r_ != 0) {
        output.writeInt32(4, r_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (u_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, u_);
      }
      if (v_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, v_);
      }
      if (w_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, w_);
      }
      if (r_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, r_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.grpc.Drones.Velocidades)) {
        return super.equals(obj);
      }
      org.example.grpc.Drones.Velocidades other = (org.example.grpc.Drones.Velocidades) obj;

      boolean result = true;
      result = result && (getU()
          == other.getU());
      result = result && (getV()
          == other.getV());
      result = result && (getW()
          == other.getW());
      result = result && (getR()
          == other.getR());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + U_FIELD_NUMBER;
      hash = (53 * hash) + getU();
      hash = (37 * hash) + V_FIELD_NUMBER;
      hash = (53 * hash) + getV();
      hash = (37 * hash) + W_FIELD_NUMBER;
      hash = (53 * hash) + getW();
      hash = (37 * hash) + R_FIELD_NUMBER;
      hash = (53 * hash) + getR();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.grpc.Drones.Velocidades parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.Drones.Velocidades parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.Drones.Velocidades parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.Drones.Velocidades parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.Drones.Velocidades parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.Drones.Velocidades parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.Drones.Velocidades parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.Drones.Velocidades parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.Drones.Velocidades parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.grpc.Drones.Velocidades parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.Drones.Velocidades parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.Drones.Velocidades parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.grpc.Drones.Velocidades prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Velocidades}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Velocidades)
        org.example.grpc.Drones.VelocidadesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.grpc.Drones.internal_static_Velocidades_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.grpc.Drones.internal_static_Velocidades_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.grpc.Drones.Velocidades.class, org.example.grpc.Drones.Velocidades.Builder.class);
      }

      // Construct using org.example.grpc.Drones.Velocidades.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        u_ = 0;

        v_ = 0;

        w_ = 0;

        r_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.grpc.Drones.internal_static_Velocidades_descriptor;
      }

      @java.lang.Override
      public org.example.grpc.Drones.Velocidades getDefaultInstanceForType() {
        return org.example.grpc.Drones.Velocidades.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.grpc.Drones.Velocidades build() {
        org.example.grpc.Drones.Velocidades result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.grpc.Drones.Velocidades buildPartial() {
        org.example.grpc.Drones.Velocidades result = new org.example.grpc.Drones.Velocidades(this);
        result.u_ = u_;
        result.v_ = v_;
        result.w_ = w_;
        result.r_ = r_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.grpc.Drones.Velocidades) {
          return mergeFrom((org.example.grpc.Drones.Velocidades)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.grpc.Drones.Velocidades other) {
        if (other == org.example.grpc.Drones.Velocidades.getDefaultInstance()) return this;
        if (other.getU() != 0) {
          setU(other.getU());
        }
        if (other.getV() != 0) {
          setV(other.getV());
        }
        if (other.getW() != 0) {
          setW(other.getW());
        }
        if (other.getR() != 0) {
          setR(other.getR());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.grpc.Drones.Velocidades parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.grpc.Drones.Velocidades) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int u_ ;
      /**
       * <code>int32 u = 1;</code>
       */
      public int getU() {
        return u_;
      }
      /**
       * <code>int32 u = 1;</code>
       */
      public Builder setU(int value) {
        
        u_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 u = 1;</code>
       */
      public Builder clearU() {
        
        u_ = 0;
        onChanged();
        return this;
      }

      private int v_ ;
      /**
       * <code>int32 v = 2;</code>
       */
      public int getV() {
        return v_;
      }
      /**
       * <code>int32 v = 2;</code>
       */
      public Builder setV(int value) {
        
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 v = 2;</code>
       */
      public Builder clearV() {
        
        v_ = 0;
        onChanged();
        return this;
      }

      private int w_ ;
      /**
       * <code>int32 w = 3;</code>
       */
      public int getW() {
        return w_;
      }
      /**
       * <code>int32 w = 3;</code>
       */
      public Builder setW(int value) {
        
        w_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 w = 3;</code>
       */
      public Builder clearW() {
        
        w_ = 0;
        onChanged();
        return this;
      }

      private int r_ ;
      /**
       * <code>int32 r = 4;</code>
       */
      public int getR() {
        return r_;
      }
      /**
       * <code>int32 r = 4;</code>
       */
      public Builder setR(int value) {
        
        r_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 r = 4;</code>
       */
      public Builder clearR() {
        
        r_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Velocidades)
    }

    // @@protoc_insertion_point(class_scope:Velocidades)
    private static final org.example.grpc.Drones.Velocidades DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.grpc.Drones.Velocidades();
    }

    public static org.example.grpc.Drones.Velocidades getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Velocidades>
        PARSER = new com.google.protobuf.AbstractParser<Velocidades>() {
      @java.lang.Override
      public Velocidades parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Velocidades(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Velocidades> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Velocidades> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.grpc.Drones.Velocidades getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Status)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool sucess = 1;</code>
     */
    boolean getSucess();
  }
  /**
   * Protobuf type {@code Status}
   */
  public  static final class Status extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Status)
      StatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Status.newBuilder() to construct.
    private Status(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Status() {
      sucess_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Status(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sucess_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.grpc.Drones.internal_static_Status_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.grpc.Drones.internal_static_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.grpc.Drones.Status.class, org.example.grpc.Drones.Status.Builder.class);
    }

    public static final int SUCESS_FIELD_NUMBER = 1;
    private boolean sucess_;
    /**
     * <code>bool sucess = 1;</code>
     */
    public boolean getSucess() {
      return sucess_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sucess_ != false) {
        output.writeBool(1, sucess_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sucess_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, sucess_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.grpc.Drones.Status)) {
        return super.equals(obj);
      }
      org.example.grpc.Drones.Status other = (org.example.grpc.Drones.Status) obj;

      boolean result = true;
      result = result && (getSucess()
          == other.getSucess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSucess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.grpc.Drones.Status parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.Drones.Status parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.Drones.Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.Drones.Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.Drones.Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.grpc.Drones.Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.grpc.Drones.Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.Drones.Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.Drones.Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.grpc.Drones.Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.grpc.Drones.Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.grpc.Drones.Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.grpc.Drones.Status prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Status}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Status)
        org.example.grpc.Drones.StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.grpc.Drones.internal_static_Status_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.grpc.Drones.internal_static_Status_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.grpc.Drones.Status.class, org.example.grpc.Drones.Status.Builder.class);
      }

      // Construct using org.example.grpc.Drones.Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sucess_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.grpc.Drones.internal_static_Status_descriptor;
      }

      @java.lang.Override
      public org.example.grpc.Drones.Status getDefaultInstanceForType() {
        return org.example.grpc.Drones.Status.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.grpc.Drones.Status build() {
        org.example.grpc.Drones.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.grpc.Drones.Status buildPartial() {
        org.example.grpc.Drones.Status result = new org.example.grpc.Drones.Status(this);
        result.sucess_ = sucess_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.grpc.Drones.Status) {
          return mergeFrom((org.example.grpc.Drones.Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.grpc.Drones.Status other) {
        if (other == org.example.grpc.Drones.Status.getDefaultInstance()) return this;
        if (other.getSucess() != false) {
          setSucess(other.getSucess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.grpc.Drones.Status parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.grpc.Drones.Status) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean sucess_ ;
      /**
       * <code>bool sucess = 1;</code>
       */
      public boolean getSucess() {
        return sucess_;
      }
      /**
       * <code>bool sucess = 1;</code>
       */
      public Builder setSucess(boolean value) {
        
        sucess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool sucess = 1;</code>
       */
      public Builder clearSucess() {
        
        sucess_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Status)
    }

    // @@protoc_insertion_point(class_scope:Status)
    private static final org.example.grpc.Drones.Status DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.grpc.Drones.Status();
    }

    public static org.example.grpc.Drones.Status getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Status>
        PARSER = new com.google.protobuf.AbstractParser<Status>() {
      @java.lang.Override
      public Status parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Status(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Status> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Status> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.grpc.Drones.Status getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Velocidades_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Velocidades_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014drones.proto\"9\n\013Velocidades\022\t\n\001u\030\001 \001(\005" +
      "\022\t\n\001v\030\002 \001(\005\022\t\n\001w\030\003 \001(\005\022\t\n\001r\030\004 \001(\005\"\030\n\006Sta" +
      "tus\022\016\n\006sucess\030\001 \001(\01028\n\013ManejoDrone\022)\n\020ma" +
      "ndaVelocidades\022\014.Velocidades\032\007.StatusB\022\n" +
      "\020org.example.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Velocidades_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Velocidades_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Velocidades_descriptor,
        new java.lang.String[] { "U", "V", "W", "R", });
    internal_static_Status_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Status_descriptor,
        new java.lang.String[] { "Sucess", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
